### ISSUE TITLE
LAB3 : Service Error In Transpiler-AI

### ISSUE THREAD

**Issue by AIdjis** [qiskit-community/ibm-quantum-challenge-2024#13]
"I am working on Lab 3, Exercise 1, and I encountered an issue when running the following cell:

circuit_ai_false = transpiler_ai_false.run(circuit)

The error message I receive is:

INFO: qiskit_transpiler_service.transpiler_service: Requesting transpile to the service
ERROR: qiskit_transpiler_service.ai.service_wrapper: Service error: 403 Client Error: Forbidden for url: ......

**Comment by matthieuml** [comment]
Not sure if this comes from the same problem, but I had the same error and fixed it by adding another environment variable for the token:
`%set_env QISKIT_IBM_TOKEN=deleteThisAndPasteYourTokenHere`

**Comment by AIdjis** [comment]
done the lab works fine now
