### ISSUE TITLE
Auth error code 3445 in Lab3 [Solved: need to use account created with IBM ID instead of 3rd parties]

### ISSUE THREAD

**Issue by iloktev** [qiskit-community/ibm-quantum-challenge-2024#14]
Hi there,
I'm getting the following error while trying to connect to QiskitRuntimeService in Lab3 'AI-Powered Transpilation':

**Login with some authorized provider required., Error code: 3445.**

As far I understand from docs, that relates to the fact I'm using IBM account made with Google Sign-in, rather than IBM ID. But there seems to be no options to re-connect IBM ID somehow to an existing account. Is there any way to proceed with the challenge?

**Comment by SandeepaDilshanAlagiyawanna** [comment]
Go to https://quantum.ibm.com/ and select your qc-2024-11 instance, then you will be able to access.

**Comment by iloktev** [comment]
Thanks for the comment, but that I initially did - doesn't seems to help actually. I am switching to another instance, then regenerating the key and put it into code - yet getting 3445. 
![image](https://github.com/qiskit-community/ibm-quantum-challenge-2024/assets/17858824/9dc0c4a9-25c7-4605-a0f7-7712abaf46ff)

**Comment by matthieuml** [comment]
Does adding channel="ibm_quantum" and token=token (not in the environment variable form) fixes it?

**Comment by iloktev** [comment]
not really, I think I tried all the possible methods found in documentation... My final guess that's related to the fact my account was initially created without IBM ID
![image](https://github.com/qiskit-community/ibm-quantum-challenge-2024/assets/17858824/d9e8d503-f1fd-4ec7-aef7-75ce083339d3)

**Comment by matthieuml** [comment]
Your token is fully visibly here, you should change it!

**Comment by SandeepaDilshanAlagiyawanna** [comment]
> Thanks for the comment, but that I initially did - doesn't seems to help actually. I am switching to another instance, then regenerating the key and put it into code - yet getting 3445. ![image](https://private-user-images.githubusercontent.com/17858824/337716518-9dc0c4a9-25c7-4605-a0f7-7712abaf46ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3ODQxNDQsIm5iZiI6MTcxNzc4Mzg0NCwicGF0aCI6Ii8xNzg1ODgyNC8zMzc3MTY1MTgtOWRjMGM0YTktMjVjNy00NjA1LWEwZjctNzcxMmFiYWY0NmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDE4MTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MzE5NDk3MDg1MWUzNzU4NjEwNTM4NzU3NTFiOTEyNmNjNjU3NGE1MzU5ZGVlODBiMDNhNDk0OGFmYzA4OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.py9FLF1rsqkBHyCutEIcNuUlwtQdLWG2kK09tOF1tZs)

Yeah, you should see the https://docs.quantum.ibm.com/transpile/qiskit-transpiler-service traspilar service docs. And then don't use the _instance_, because _ibm_brisbane_ is not available for that instance =\ I got wrong also.

_**Hint:- Lab03 Ex1- did not require any of those tokens**_

**Comment by HuangJunye** [comment]
@iloktev Sorry to hear that you are facing this issue. The solution should be exactly what you said. Can you create an IBMid using the same email that is associated with your IBM Quantum account and login again with the IBMid? That should automatically be the same account. If this doesn't resolve the issue, please ping me here again. Thank you!

**Comment by iloktev** [comment]
Hi HuangJunye, no worries and thanks for the answer! I've actually created another account with new IBM ID (and another email, as I thought the system won't allow me to use gmail as 'work email') and passed again all the labs till #3. Now it works perfectly. Thanks again!
