### ISSUE TITLE
Issues submitting ex_5, lab1

### ISSUE THREAD

**Issue by jgonzal3** [qiskit-community/ibm-quantum-challenge-2024#28]
I have built the response for lab_1_ex_5, but when I submit the answer for grading, the grader returns that the response is incorrect. I have used the correct backend (Sherbrooke), the optimization, I have tried 0,1,2 and 3. I also set the circuit in the ISA as in the previous exercise, ansatz. There is not much place to make a mistake, but the grader does not accept the answer.

I ran the next instruction, and I got the ISA representation of the ansatz circuit.

Any help will be greatly appreciated.

**Comment by lefodor** [comment]
I have the same problem, some instructions would be helpful about what is incorrect in the submitted solution.
`Submitting your answer. Please wait...
Oops 😕! Sorry, your answer is incorrect. Please try again.
Please review your answer and try again. `

**Comment by jgonzal3** [comment]
Well, after carefully checking the ansatz, I had a typo. If anyone is experiencing this issue, review the definition very carefully. You can pass q4, but q5 breaks

**Comment by jgonzal3** [comment]
Close it.
