### ISSUE TITLE
"The QPY format version being read, 12, isn't supported by this Qiskit version. Please upgrade your version of Qiskit to load this QPY payload"

### ISSUE THREAD

**Issue by andercrespoo** [qiskit-community/ibm-quantum-challenge-2024#3]
Qiskit version: 1.1.0

Hi I'm a new comer to the IBM quantum challenge and I run into this problem while verifying exercise 1 in lab 1. While running the code `grade_lab1_ex1(qc)` the grader returned the error "The QPY format version being read, 12, isn't supported by this Qiskit version. Please upgrade your version of Qiskit to load this QPY payload".

 I saw in another post that this problem may come from the mismatch between the QPY and the `qiskit-ibm-runtime` versions, but the error in the post I read said 10 instead of 12, as in my error, and the solution given in that post didn't work for me. 

post: https://github.com/Qiskit/qiskit-ibm-runtime/issues/1332#issue-2098337350

Im running on a MacBook Pro with an M1 pro apple silicon and another colleague with an M2 MacBook Air is also running into this problem so there may be some compatibility problems too.

Any suggestions on how to fix this?

**Comment by Raiden-Makoto** [comment]
it says to use qiskit version 1.0.2. I am using M1 MacBook Air and everything works fine.

**Comment by andercrespoo** [comment]
Thank you!! This solved the error.

 In case someone faces the same error I uninstalled qiksit from the terminal with`pip uninstall qiskit` and then I installed the 1.0.2 version with `pip install qiskit==1.0.2` and then also in the challenge, just to make sure I had the same version in Jupyter and in the environment I reinstalled qiskit 1.0.2 with `!pip install qiskit==1.0.2` 

To check the qiskit version in the terminal you can use `pip freeze qiskit` and then search for the qiskit version. And to check what version you have in python you can `import qiskit` in your file and then check with `qiskit.__version__`, if you have qiskit 1.1.0 the grader won't work, at least this happened for me and my colleague.

Hope this helps!! Thank you so much!

**Comment by andercrespoo** [comment]
I'm closing the issue
